export const NewStaffActionTypes = {
    GET_LIST_NEW_STAFF: "GET_LIST_NEW_STAFF",
    GET_LIST_NEW_STAFF_SUCCESS: "GET_LIST_NEW_STAFF_SUCCESS",
    GET_LIST_NEW_STAFF_FAILED: "GET_LIST_NEW_STAFF_FAILED",
};

export const AddressActionTypes = {
    // PROVINCE
    GET_LIST_PROVINCE: "GET_LIST_PROVINCE",
    GET_LIST_PROVINCE_SUCCESS: "GET_LIST_PROVINCE_SUCCESS",
    GET_LIST_PROVINCE_FAILED: "GET_LIST_PROVINCE_FAILED",

    // DISTRICT
    GET_LIST_DISTRICT: "GET_LIST_DISTRICT",
    GET_LIST_DISTRICT_SUCCESS: "GET_LIST_DISTRICT_SUCCESS",
    GET_LIST_DISTRICT_FAILED: "GET_LIST_DISTRICT_FAILED",

    // COMMUNE
    GET_LIST_COMMUNE: "GET_LIST_COMMUNE",
    GET_LIST_COMMUNE_SUCCESS: "GET_LIST_COMMUNE_SUCCESS",
    GET_LIST_COMMUNE_FAILED: "GET_LIST_DISTRICT_FAILED",
};